[
    [347, u'COBAEH'],
    [580, u'SAGARPA'],
    [398, u'INE'],
    [557, u'SECRETARIA DE EDUCACION PUEBLA SNTE 23 FEDERAL'],
    [346, u'SECRETARIA DE EDUCACION GUERRERO'],
    [358, u'IMSS PENSIONADOS'],
    [327, u'GOBIERNO DE HIDALGO'],
    [419, u'IMSS PARITARIA QUINCENAL'],
    [357, u'IMSS JUBILADOS'],
    [420, u'SEDESOL'],
    [421, u'PEMEX'],
    [322, u'GOBIERNO DEL DISTRITO FEDERAL']
]